# Generated by Django 4.2.20 on 2025-05-06 06:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter a product name.', max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Baskets',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pen', 'Pending'), ('con', 'confirmed'), ('can', 'Canceled')], default='pen', help_text='Shopping Basket Status', max_length=3)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='shopping.products')),
            ],
        ),
    ]
