# Generated by Django 4.2.20 on 2025-05-06 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_basket_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='status',
            new_name='basket_status',
        ),
    ]
