# Generated by Django 4.2.20 on 2025-05-06 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_rename_status_basket_basket_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='userid',
            new_name='user',
        ),
    ]
