# Generated by Django 4.2.20 on 2025-05-07 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_basketitem_created_at_product_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
