# Generated by Django 4.2.20 on 2025-05-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_remove_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='basket_status',
            field=models.CharField(choices=[('sho', 'Shopping'), ('pen', 'Pending'), ('con', 'Confirmed'), ('can', 'Canceled')], default='pen', help_text='Shopping Basket Status', max_length=3),
        ),
    ]
